# Generated by Django 4.2.10 on 2025-05-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_proxy_password_alter_proxy_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
