# Generated by Django 4.2.10 on 2025-05-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_bulkuploadaccount_bulkuploadtask_bulkvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='current_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_accounts', to='uploader.proxy'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='assigned_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_assignment', to='uploader.instagramaccount'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='proxy_type',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('SOCKS5', 'SOCKS5'), ('HTTPS', 'HTTPS')], default='HTTP', max_length=10),
        ),
        migrations.AddField(
            model_name='proxy',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('banned', 'Забанен'), ('checking', 'Проверяется')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='host',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.IntegerField(),
        ),
    ]
