# Generated by Django 4.2.10 on 2025-05-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_instagramaccount_current_proxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='browser_fingerprint',
            field=models.JSONField(blank=True, help_text='Complete browser fingerprint data as JSON', null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='canvas_fingerprint_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='fonts',
            field=models.JSONField(blank=True, help_text='List of available fonts', null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='language',
            field=models.CharField(blank=True, help_text='Example: en-US, ru-RU', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='plugins',
            field=models.JSONField(blank=True, help_text='List of browser plugins', null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='screen_resolution',
            field=models.CharField(blank=True, help_text='Format: WidthxHeight, e.g. 1920x1080', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='timezone',
            field=models.CharField(blank=True, help_text='Example: Europe/London, America/New_York', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='webgl_renderer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='webgl_vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
