# Generated by Django 4.2.10 on 2025-05-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_instagramaccount_browser_fingerprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user_agent', models.TextField()),
                ('screen_resolution', models.CharField(max_length=20)),
                ('webgl_vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('webgl_renderer', models.CharField(blank=True, max_length=100, null=True)),
                ('canvas_fingerprint_data', models.TextField(blank=True, null=True)),
                ('fonts', models.JSONField(blank=True, null=True)),
                ('plugins', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(default='en-US', max_length=10)),
                ('timezone', models.CharField(default='Europe/London', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='browser_fingerprint',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='canvas_fingerprint_data',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='fonts',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='language',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='plugins',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='screen_resolution',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='webgl_renderer',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='webgl_vendor',
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='fingerprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='uploader.browserfingerprint'),
        ),
    ]
