# Generated by Django 4.2.10 on 2025-05-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0008_browserfingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='custom_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='mentions',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='title',
            field=models.CharField(default='Upload', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadtask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WARMING_UP', 'Warming Up'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
