# Generated by Django 4.2.10 on 2025-05-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_uploadtask_completed_at_uploadtask_custom_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadtask',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='custom_data',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='location',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='mentions',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='title',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='user',
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='dolphin_profile_id',
            field=models.CharField(blank=True, help_text='Dolphin Anty browser profile ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned'), ('checking', 'Checking')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
