# Generated by Django 5.1.5 on 2025-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0013_bulkuploadtask_default_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadaccount',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PHONE_VERIFICATION_REQUIRED', 'Phone Verification Required')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='bulkuploadtask',
            name='default_location',
            field=models.CharField(blank=True, default='', help_text='Шаблон локации для копирования в видео (не применяется автоматически)', max_length=200),
        ),
        migrations.AlterField(
            model_name='bulkuploadtask',
            name='default_mentions',
            field=models.TextField(blank=True, default='', help_text='Шаблон упоминаний для копирования в видео (не применяются автоматически)'),
        ),
    ]
