# Generated by Django 5.1.5 on 2025-05-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0015_alter_instagramaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadaccount',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PHONE_VERIFICATION_REQUIRED', 'Phone Verification Required'), ('HUMAN_VERIFICATION_REQUIRED', 'Human Verification Required')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('LIMITED', 'Limited'), ('INACTIVE', 'Inactive'), ('PHONE_VERIFICATION_REQUIRED', 'Phone Verification Required'), ('HUMAN_VERIFICATION_REQUIRED', 'Human Verification Required')], default='ACTIVE', max_length=30),
        ),
    ]
