# Generated by Django 5.1.5 on 2025-08-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0016_merge_0015_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkLoginTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bulk Login', max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIALLY_COMPLETED', 'Partially Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='BulkLoginAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PHONE_VERIFICATION_REQUIRED', 'Phone Verification Required'), ('HUMAN_VERIFICATION_REQUIRED', 'Human Verification Required'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=30)),
                ('log', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_logins', to='uploader.instagramaccount')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_login_used_in', to='uploader.proxy')),
                ('bulk_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='uploader.bulklogintask')),
            ],
        ),
    ]
