# Generated by Django 5.1.5 on 2025-08-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0017_bulklogintask_bulkloginaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioLinkChangeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bio Link Change', max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('link_url', models.URLField(max_length=500)),
                ('delay_min_sec', models.IntegerField(default=15)),
                ('delay_max_sec', models.IntegerField(default=45)),
                ('concurrency', models.IntegerField(default=1)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BioLinkChangeTaskAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('log', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_tasks', to='uploader.instagramaccount')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bio_used_in', to='uploader.proxy')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='uploader.biolinkchangetask')),
            ],
        ),
    ]
