# Generated by Django 5.1.5 on 2025-08-08 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0018_bulkuploadaccount_uploaded_failed_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarChangeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Avatar Change', max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('strategy', models.CharField(choices=[('random_reuse', 'Random reuse when images < accounts'), ('one_to_one', 'One image per account (same order)')], default='random_reuse', max_length=20)),
                ('delay_min_sec', models.IntegerField(default=15)),
                ('delay_max_sec', models.IntegerField(default=45)),
                ('concurrency', models.IntegerField(default=1)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='AvatarChangeTaskAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('log', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_tasks', to='uploader.instagramaccount')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_used_in', to='uploader.proxy')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='uploader.avatarchangetask')),
            ],
        ),
        migrations.CreateModel(
            name='AvatarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bot/avatars/')),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='uploader.avatarchangetask')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InstagramDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_settings', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('session_settings', models.JSONField(blank=True, null=True)),
                ('session_file', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_avatar_change_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='uploader.instagramaccount')),
            ],
            options={
                'verbose_name': 'Instagram device',
                'verbose_name_plural': 'Instagram devices',
            },
        ),
    ]
