# Generated by Django 5.1.5 on 2025-08-12 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0019_warmuptask_warmuptaskaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramaccount',
            options={},
        ),
        migrations.CreateModel(
            name='DolphinProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, max_length=100)),
                ('payload_json', models.JSONField()),
                ('response_json', models.JSONField()),
                ('meta_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dolphin_snapshot', to='uploader.instagramaccount')),
            ],
            options={
                'verbose_name': 'Instagram account',
                'verbose_name_plural': 'Instagram accounts',
            },
        ),
    ]
