# Generated by Django 5.1.5 on 2025-08-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0021_reelstask_reelstaskaccount_reelsvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reelstaskaccount',
            name='task',
        ),
        migrations.RemoveField(
            model_name='reelsvideo',
            name='task',
        ),
        migrations.RemoveField(
            model_name='reelstaskaccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='reelstaskaccount',
            name='proxy',
        ),
        migrations.DeleteModel(
            name='ReelsTask',
        ),
        migrations.DeleteModel(
            name='ReelsVideo',
        ),
        migrations.DeleteModel(
            name='ReelsTaskAccount',
        ),
    ]
