# Generated by Django 5.1.5 on 2025-09-01 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        ('uploader', '0022_remove_reelstaskaccount_task_remove_reelsvideo_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='cabinet.client'),
        ),
        migrations.CreateModel(
            name='HashtagAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(db_index=True, max_length=150)),
                ('total_medias_reported', models.IntegerField(default=0)),
                ('fetched_medias', models.IntegerField(default=0)),
                ('analyzed_medias', models.IntegerField(default=0)),
                ('pages_loaded', models.IntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('average_views', models.FloatField(default=0.0)),
                ('info_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hashtag analytics',
                'verbose_name_plural': 'Hashtag analytics',
                'indexes': [models.Index(fields=['hashtag', 'created_at'], name='uploader_ha_hashtag_33afdb_idx')],
            },
        ),
    ]
