# Generated by Django 5.1.5 on 2025-09-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0024_instagramaccount_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtaganalytics',
            name='engagement_rate',
            field=models.FloatField(default=0.0, help_text='(likes+comments)/views, 0 if views == 0'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='total_comments',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='total_likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AccountAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_videos', models.IntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_comments', models.BigIntegerField(default=0)),
                ('average_views', models.FloatField(default=0.0)),
                ('engagement_rate', models.FloatField(default=0.0, help_text='(likes+comments)/views, 0 if views == 0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='uploader.instagramaccount')),
            ],
            options={
                'verbose_name': 'Account analytics',
                'verbose_name_plural': 'Account analytics',
                'indexes': [models.Index(fields=['account', 'created_at'], name='uploader_ac_account_8497fa_idx')],
            },
        ),
    ]
