# Generated by Django 5.1.5 on 2025-09-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0025_hashtaganalytics_engagement_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='ip_change_url',
            field=models.URLField(blank=True, help_text='URL for changing proxy IP address', max_length=500, null=True),
        ),
    ]
