# Generated by Django 5.1.5 on 2025-09-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0026_proxy_ip_change_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='host',
            field=models.CharField(help_text='Proxy host (IP address or domain name)', max_length=255),
        ),
    ]
