# Generated by Django 5.1.5 on 2025-09-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0027_alter_proxy_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='external_ip',
            field=models.GenericIPAddressField(blank=True, help_text='External IP address when using this proxy', null=True),
        ),
    ]
