# Generated by Django 5.1.5 on 2025-10-01 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_calculationhistory_client_name'),
        ('uploader', '0028_proxy_external_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeShortsBulkUploadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='YouTube Shorts Bulk Upload', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIALLY_COMPLETED', 'Partially Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log', models.TextField(blank=True, default='')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('default_visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('PRIVATE', 'Private')], default='PUBLIC', help_text='Default visibility for uploaded shorts', max_length=20)),
                ('default_category', models.CharField(blank=True, default='', help_text='Default YouTube category', max_length=50)),
                ('default_tags', models.TextField(blank=True, default='', help_text='Default tags, one per line')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='YouTube/Google account email', max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('channel_name', models.CharField(blank=True, default='', max_length=200)),
                ('channel_id', models.CharField(blank=True, default='', help_text='YouTube channel ID', max_length=200)),
                ('recovery_email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('tfa_secret', models.CharField(blank=True, help_text='2FA secret for TOTP', max_length=100, null=True)),
                ('dolphin_profile_id', models.CharField(blank=True, help_text='Dolphin Anty browser profile ID', max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('LIMITED', 'Limited'), ('INACTIVE', 'Inactive'), ('PHONE_VERIFICATION_REQUIRED', 'Phone Verification Required'), ('HUMAN_VERIFICATION_REQUIRED', 'Human Verification Required'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=30)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('locale', models.CharField(default='en_US', help_text='Browser locale, e.g. en_US, ru_RU, es_ES', max_length=5)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_accounts', to='cabinet.client')),
                ('current_proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_youtube_accounts', to='uploader.proxy')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_accounts', to='uploader.proxy')),
            ],
            options={
                'verbose_name': 'YouTube Account',
                'verbose_name_plural': 'YouTube Accounts',
            },
        ),
        migrations.CreateModel(
            name='YouTubeShortsBulkUploadAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PHONE_VERIFICATION_REQUIRED', 'Phone Verification Required'), ('HUMAN_VERIFICATION_REQUIRED', 'Human Verification Required'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=30)),
                ('log', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_success_count', models.IntegerField(default=0)),
                ('uploaded_failed_count', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='uploader.youtubeaccount')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_bulk_used_in', to='uploader.proxy')),
                ('bulk_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='uploader.youtubeshortsbulkuploadtask')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeShortsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='youtube/shorts_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('visibility', models.CharField(blank=True, default='', help_text='Visibility for this video (overrides default)', max_length=20)),
                ('category', models.CharField(blank=True, default='', help_text='Category for this video (overrides default)', max_length=50)),
                ('tags', models.TextField(blank=True, default='', help_text='Tags for this video, one per line (overrides default)')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_videos', to='uploader.youtubeshortsbulkuploadaccount')),
                ('bulk_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='uploader.youtubeshortsbulkuploadtask')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeShortsVideoTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Video title (max 100 chars for Shorts)', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Video description')),
                ('used', models.BooleanField(default=False)),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_data', to='uploader.youtubeshortsvideo')),
                ('bulk_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='uploader.youtubeshortsbulkuploadtask')),
            ],
        ),
    ]
