# Generated by Django 5.1.5 on 2025-10-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0029_youtubeshortsbulkuploadtask_youtubeaccount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dolphinprofilesnapshot',
            options={'verbose_name': 'Dolphin Profile Snapshot', 'verbose_name_plural': 'Dolphin Profile Snapshots'},
        ),
        migrations.AlterModelOptions(
            name='instagramaccount',
            options={'verbose_name': 'Instagram account', 'verbose_name_plural': 'Instagram accounts'},
        ),
        migrations.CreateModel(
            name='YouTubeCookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies_data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to='uploader.youtubeaccount')),
            ],
            options={
                'verbose_name': 'YouTube cookies',
                'verbose_name_plural': 'YouTube cookies',
            },
        ),
        migrations.CreateModel(
            name='YouTubeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_settings', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('session_settings', models.JSONField(blank=True, null=True)),
                ('session_file', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='uploader.youtubeaccount')),
            ],
            options={
                'verbose_name': 'YouTube device',
                'verbose_name_plural': 'YouTube devices',
            },
        ),
    ]
