# Generated by Django 5.1.5 on 2025-10-06 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0030_alter_dolphinprofilesnapshot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dolphinprofilesnapshot',
            name='account',
        ),
        migrations.AddField(
            model_name='dolphinprofilesnapshot',
            name='instagram_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dolphin_snapshot', to='uploader.instagramaccount'),
        ),
        migrations.AddField(
            model_name='dolphinprofilesnapshot',
            name='youtube_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dolphin_snapshot', to='uploader.youtubeaccount'),
        ),
    ]
