# Generated by Django 5.1.5 on 2025-10-06 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0031_remove_dolphinprofilesnapshot_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dolphincookierobottask',
            name='account',
        ),
        migrations.AddField(
            model_name='dolphincookierobottask',
            name='instagram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_robot_tasks', to='uploader.instagramaccount'),
        ),
        migrations.AddField(
            model_name='dolphincookierobottask',
            name='youtube_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_robot_tasks', to='uploader.youtubeaccount'),
        ),
    ]
