# Generated by Django 5.1.5 on 2025-10-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0033_clientanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientanalytics',
            name='instagram_reels_views',
            field=models.BigIntegerField(blank=True, default=0, help_text='Instagram reels views'),
        ),
        migrations.AlterField(
            model_name='clientanalytics',
            name='instagram_stories_views',
            field=models.BigIntegerField(blank=True, default=0, help_text='Instagram stories views'),
        ),
        migrations.AlterField(
            model_name='clientanalytics',
            name='tiktok_profile_views',
            field=models.BigIntegerField(blank=True, default=0, help_text='TikTok profile views'),
        ),
        migrations.AlterField(
            model_name='clientanalytics',
            name='tiktok_video_views',
            field=models.BigIntegerField(blank=True, default=0, help_text='TikTok video views'),
        ),
        migrations.AlterField(
            model_name='clientanalytics',
            name='youtube_subscribers',
            field=models.BigIntegerField(blank=True, default=0, help_text='YouTube subscribers'),
        ),
        migrations.AlterField(
            model_name='clientanalytics',
            name='youtube_watch_time',
            field=models.BigIntegerField(blank=True, default=0, help_text='YouTube watch time (minutes)'),
        ),
    ]
