# Generated by Django 5.1.5 on 2025-10-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0034_alter_clientanalytics_instagram_reels_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientanalytics',
            name='hashtag',
            field=models.CharField(blank=True, default='', help_text='Specific hashtag for this analytics (optional)', max_length=100),
        ),
    ]
