# Generated by Django 5.1.5 on 2025-10-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_calculationhistory_client_name'),
        ('uploader', '0035_clientanalytics_hashtag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientanalytics',
            unique_together={('client', 'social_network', 'period_start', 'period_end', 'hashtag')},
        ),
    ]
