# Generated by Django 5.1.5 on 2025-10-06 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_calculationhistory_client_name'),
        ('uploader', '0036_alter_clientanalytics_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtaganalytics',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client for manual analytics (null for automatic hashtag analysis)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_analytics', to='cabinet.client'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who created this manual analytics entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hashtag_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='growth_rate',
            field=models.FloatField(default=0.0, help_text='Follower growth rate (%)'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='instagram_reels_views',
            field=models.BigIntegerField(blank=True, default=0, help_text='Instagram reels views'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='instagram_stories_views',
            field=models.BigIntegerField(blank=True, default=0, help_text='Instagram stories views'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True if this is manually entered analytics, False if automatic hashtag analysis'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about the analytics'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='period_end',
            field=models.DateField(blank=True, help_text='End date of analytics period', null=True),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start date of analytics period', null=True),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='social_network',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok')], default='INSTAGRAM', help_text='Social network platform', max_length=20),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='tiktok_profile_views',
            field=models.BigIntegerField(blank=True, default=0, help_text='TikTok profile views'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='tiktok_video_views',
            field=models.BigIntegerField(blank=True, default=0, help_text='TikTok video views'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='total_followers',
            field=models.BigIntegerField(default=0, help_text='Current follower count'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='total_shares',
            field=models.BigIntegerField(default=0, help_text='Total shares/reposts'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='youtube_subscribers',
            field=models.BigIntegerField(blank=True, default=0, help_text='YouTube subscribers'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='youtube_watch_time',
            field=models.BigIntegerField(blank=True, default=0, help_text='YouTube watch time (minutes)'),
        ),
        migrations.AlterUniqueTogether(
            name='hashtaganalytics',
            unique_together={('client', 'social_network', 'hashtag', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='hashtaganalytics',
            index=models.Index(fields=['client', 'social_network', 'created_at'], name='uploader_ha_client__9b90d0_idx'),
        ),
        migrations.AddIndex(
            model_name='hashtaganalytics',
            index=models.Index(fields=['is_manual', 'created_at'], name='uploader_ha_is_manu_17d40c_idx'),
        ),
    ]
