# Generated by Django 5.1.5 on 2025-10-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0037_hashtaganalytics_client_hashtaganalytics_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtaganalytics',
            name='growth_rate',
            field=models.FloatField(blank=True, default=0.0, help_text='Follower growth rate (%)'),
        ),
        migrations.AlterField(
            model_name='hashtaganalytics',
            name='total_comments',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hashtaganalytics',
            name='total_followers',
            field=models.BigIntegerField(blank=True, default=0, help_text='Current follower count'),
        ),
        migrations.AlterField(
            model_name='hashtaganalytics',
            name='total_likes',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hashtaganalytics',
            name='total_shares',
            field=models.BigIntegerField(blank=True, default=0, help_text='Total shares/reposts'),
        ),
        migrations.AlterField(
            model_name='hashtaganalytics',
            name='total_views',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
