# Generated by Django 5.1.5 on 2025-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0038_alter_hashtaganalytics_growth_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtaganalytics',
            name='avg_likes_per_account',
            field=models.FloatField(blank=True, default=0.0, help_text='Average likes per account'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='avg_likes_per_video',
            field=models.FloatField(blank=True, default=0.0, help_text='Average likes per video'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='avg_videos_per_account',
            field=models.FloatField(blank=True, default=0.0, help_text='Average videos per account'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='avg_views_per_account',
            field=models.FloatField(blank=True, default=0.0, help_text='Average views per account'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='avg_views_per_video',
            field=models.FloatField(blank=True, default=0.0, help_text='Average views per video'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='max_likes_per_account',
            field=models.BigIntegerField(blank=True, default=0, help_text='Maximum likes per account'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='max_likes_per_video',
            field=models.BigIntegerField(blank=True, default=0, help_text='Maximum likes per video'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='max_videos_per_account',
            field=models.IntegerField(blank=True, default=0, help_text='Maximum videos per account'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='max_views_per_account',
            field=models.BigIntegerField(blank=True, default=0, help_text='Maximum views per account'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='max_views_per_video',
            field=models.BigIntegerField(blank=True, default=0, help_text='Maximum views per video'),
        ),
        migrations.AddField(
            model_name='hashtaganalytics',
            name='total_accounts',
            field=models.IntegerField(blank=True, default=0, help_text='Total number of accounts analyzed'),
        ),
    ]
