# Generated by Django 5.1.5 on 2025-10-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0039_add_advanced_account_metrics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hashtaganalytics',
            unique_together=set(),
        ),
    ]
