# Generated by Django 5.1.5 on 2025-10-06 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0043_merge_20251007_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtaganalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientanalytics',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when analytics data was collected'),
        ),
    ]
