# Generated by Django 5.1.5 on 2025-10-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0045_safe_add_missing_columns'),
        ('uploader', '0046_merge_20251006_2342'),
    ]

    operations = [
    ]
