# Generated by Django 5.1.5 on 2025-10-08 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0047_merge_20251008_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for UI display', max_length=7)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='clientanalytics',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when analytics data was collected'),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this account', related_name='accounts', to='uploader.tag'),
        ),
    ]
