# Generated by Django 5.1.5 on 2025-10-08 09:32

from django.db import migrations


def create_default_tags(apps, schema_editor):
    Tag = apps.get_model('uploader', 'Tag')
    
    default_tags = [
        {'name': 'Memes', 'color': '#ff6b6b', 'description': 'Memes and funny content'},
        {'name': 'Sport', 'color': '#4ecdc4', 'description': 'Sports and fitness content'},
        {'name': 'Films', 'color': '#45b7d1', 'description': 'Movies and entertainment'},
        {'name': 'Porn', 'color': '#f9ca24', 'description': 'Adult content'},
        {'name': 'Casino', 'color': '#6c5ce7', 'description': 'Gambling and casino content'},
        {'name': 'Games', 'color': '#a55eea', 'description': 'Gaming content'},
        {'name': 'Streams', 'color': '#26de81', 'description': 'Live streaming content'},
    ]
    
    for tag_data in default_tags:
        Tag.objects.get_or_create(
            name=tag_data['name'],
            defaults={
                'color': tag_data['color'],
                'description': tag_data['description']
            }
        )


def remove_default_tags(apps, schema_editor):
    Tag = apps.get_model('uploader', 'Tag')
    Tag.objects.filter(name__in=['Memes', 'Sport', 'Films', 'Porn', 'Casino', 'Games', 'Streams']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0048_add_tags_to_accounts'),
    ]

    operations = [
        migrations.RunPython(create_default_tags, remove_default_tags),
    ]
