# Generated by Django 5.1.5 on 2025-10-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0049_create_default_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='tags',
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Tag for categorizing this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='uploader.tag'),
        ),
    ]
