# Generated by Django 5.1.5 on 2025-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0050_change_tags_to_single_tag'),
    ]

    operations = [
        # Empty migration to sync with Windows server
        # The updated_at field already exists in the database
    ]
