# Generated by Django 5.1.5 on 2025-10-08 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0053_fix_hashtaganalytics_null_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeaccount',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Tag for categorizing this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_accounts', to='uploader.tag'),
        ),
    ]
