# Generated by Django 5.1.5 on 2025-10-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0054_add_tag_to_youtube_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtaganalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='youtubeshortsvideo',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description for this video (overrides default)'),
        ),
        migrations.AddField(
            model_name='youtubeshortsvideo',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title for this video (overrides default)', max_length=100),
        ),
    ]
