# Generated by Django 5.1.5 on 2025-10-14 13:51

from django.db import migrations, models


def safe_add_updated_at(apps, schema_editor):
    """Safely add updated_at column if it doesn't exist"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Check if updated_at column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='uploader_hashtaganalytics' 
            AND column_name='updated_at'
        """)
        updated_at_exists = cursor.fetchone() is not None
        
        # Add updated_at if it doesn't exist
        if not updated_at_exists:
            cursor.execute("""
                ALTER TABLE uploader_hashtaganalytics 
                ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            """)
            print("Added updated_at column to HashtagAnalytics")
        else:
            print("updated_at column already exists in HashtagAnalytics")


def reverse_safe_add_updated_at(apps, schema_editor):
    """Remove updated_at column if it exists"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Check if updated_at column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='uploader_hashtaganalytics' 
            AND column_name='updated_at'
        """)
        updated_at_exists = cursor.fetchone() is not None
        
        # Remove updated_at if it exists
        if updated_at_exists:
            cursor.execute("""
                ALTER TABLE uploader_hashtaganalytics 
                DROP COLUMN updated_at
            """)
            print("Removed updated_at column from HashtagAnalytics")


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0054_add_tag_to_youtube_account'),
    ]

    operations = [
        migrations.RunPython(
            safe_add_updated_at,
            reverse_safe_add_updated_at,
        ),
        migrations.AddField(
            model_name='youtubeshortsvideo',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description for this video (overrides default)'),
        ),
        migrations.AddField(
            model_name='youtubeshortsvideo',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title for this video (overrides default)', max_length=100),
        ),
    ]
