# Generated by Django 5.1.5 on 2025-10-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0055_add_youtube_shorts_video_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeshortsvideo',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Video description'),
        ),
        migrations.AlterField(
            model_name='youtubeshortsvideo',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Video title', max_length=200),
        ),
    ]
