"""Domain-specific exceptions (extend as needed)."""
class LoginError(Exception): ...
class UploadError(Exception): ...
class VerificationRequired(Exception): ...
class FileInputNotFound(Exception): ...
class CropError(Exception): ...
