"""
Centralized selectors registry (auto-filled heuristically from your monolith).
This file is SAFE: values come from your code, but you can prune/rename anytime.
"""
from typing import Dict, List

UPLOAD_SELECTORS: Dict[str, List[str]] = {
    "generic": [
  "[ASYNC_UPLOAD] [FOLDER] File dialog opened after retry - success!",
  "[ASYNC_UPLOAD] [OK] Success after retry with page refresh!",
  "[ASYNC_UPLOAD] [CLIPBOARD] Menu appeared after enhanced delay",
  "[ASYNC_UPLOAD] [SEARCH] Performing initial page readiness check...",
  "[ASYNC_REELS_DIALOG] [OK] Dialog closed (element no longer accessible)",
  "[ASYNC_UPLOAD] [FAIL] Failed to find file input",
  "[ASYNC_UPLOAD] [RETRY] Attempting enhanced broader upload interface detection...",
  "[ASYNC_UPLOAD] [FAIL] Failed to click Share button",
  "[ASYNC_UPLOAD] [RETRY] Using alternative navigation: direct URL",
  "[ASYNC_UPLOAD] Pressing Enter for line break...",
  "[ASYNC_UPLOAD] [WARN] Initial page readiness check failed, but proceeding...",
  "[ASYNC_UPLOAD] [RETRY] Refreshing page...",
  "//",
  "[ASYNC_UPLOAD] [FAIL] Failed to navigate to upload interface",
  "[ASYNC_UPLOAD] [START] Starting enhanced navigation to upload interface",
  "(element) => element.click()",
  "[ASYNC_UPLOAD] [OK] Successfully navigated to upload interface",
  "[ASYNC_REELS_DIALOG] [WARN] Dialog still visible after click",
  "[ASYNC_UPLOAD] [TEXT] Starting metadata addition (like sync version)...",
  "[ASYNC_UPLOAD] [OK] File input elements are ready for upload",
  "[ASYNC_UPLOAD] [RETRY] First attempt failed, trying retry with page refresh...",
  "[ASYNC_UPLOAD] [WARN] Page not ready, but proceeding with navigation...",
  "[ASYNC_REELS_DIALOG] [FAIL] Found dialog but no OK button",
  "[ASYNC_UPLOAD] [FAIL] Not on Instagram domain, cannot use direct URL",
  "[ASYNC_UPLOAD] No caption text provided",
  "[ASYNC_UPLOAD] [OK] Initial page readiness check passed",
  "[ASYNC_UPLOAD] [RETRY] Clicking Next buttons (like sync version)...",
  "[ASYNC_UPLOAD] [SEARCH] Looking for upload button after refresh...",
  "[ASYNC_UPLOAD] [START] Clicking Share button...",
  "[ASYNC_UPLOAD] [START] Starting enhanced post-upload click handling...",
  "[ASYNC_UPLOAD] [RETRY] Trying alternative navigation method...",
  "[ASYNC_REELS_DIALOG] [OK] Clicked OK button",
  "[ASYNC_UPLOAD] [WARN] Upload button not visible, waiting briefly...",
  "[ASYNC_UPLOAD] [WARN] Upload button not found after refresh, trying alternative navigation...",
  "[ASYNC_UPLOAD] [WARN] Caption field not found",
  "[ASYNC_UPLOAD] 🖱️ Clicking upload button after refresh...",
  "[ASYNC_REELS_DIALOG] [WARN] No Reels dialog found, continuing...",
  "[ASYNC_UPLOAD] [CLIPBOARD] Menu appeared after retry - selecting post option",
  "[ASYNC_REELS_DIALOG] [SEARCH] Checking for Reels dialog...",
  "[ASYNC_UPLOAD] [WARN] Upload button not found, trying alternative navigation...",
  "[ASYNC_UPLOAD] [OK] Caption set successfully",
  "[ASYNC_UPLOAD] [WARN] Standard navigation failed, trying alternative...",
  "[ASYNC_UPLOAD] [OK] File dialog appeared after clicking indicator!",
  "[ASYNC_UPLOAD] [EYES] Observing page changes...",
  "[ASYNC_UPLOAD] [FOLDER] File dialog appeared after enhanced delay",
  "[ASYNC_UPLOAD] [CLIPBOARD] Dropdown menu detected - selecting post option",
  "[ASYNC_REELS_DIALOG] [OK] Dialog closed successfully",
  "[ASYNC_UPLOAD] [WARN] No file input elements found after navigation",
  "[ASYNC_UPLOAD] [RETRY] Starting retry with page refresh...",
  "[ASYNC_UPLOAD] [WARN] Could not detect upload interface with enhanced detection",
  "[ASYNC_UPLOAD] [RETRY] Final broader detection attempt after retry...",
  "[ASYNC_UPLOAD] [FOLDER] File dialog opened directly - no menu needed",
  "[ASYNC_UPLOAD] [WARN] Direct URL navigation didn't show file dialog",
  "[ASYNC_UPLOAD] [FAIL] All retry attempts failed",
  "[ASYNC_UPLOAD] [OK] Video file selected successfully",
  "[ASYNC_UPLOAD] [OK] Verifying upload success...",
  "[ASYNC_UPLOAD] [BRAIN] Starting navigation to upload page",
  "[ASYNC_UPLOAD] [WARN] Neither menu nor file dialog detected, trying enhanced broader detection...",
  "[ASYNC_UPLOAD] [FAIL] Failed to handle crop",
  "[ASYNC_UPLOAD] [FAIL] Alternative navigation failed after all retry attempts",
  "[ASYNC_UPLOAD] [OK] Successfully navigated to upload page via direct URL",
  "[ASYNC_UPLOAD] [FAIL] Upload button still not found after retry",
  "input[type=\"file\"]"
]
}

DIALOG_SELECTORS: Dict[str, List[str]] = {
    "file_input": [
  "[ASYNC_UPLOAD] 🔘 Strategy 3: Button-based search...",
  "[ASYNC_UPLOAD] 🏗️ Searching within dialog structure...",
  "[ASYNC_UPLOAD] 🌐 Strategy 6: Broad search with filtering...",
  "[ASYNC_UPLOAD] [OK] Found file input via broad search",
  "[ASYNC_UPLOAD] 🎨 Strategy 5: Instagram CSS patterns...",
  "//",
  "[ASYNC_UPLOAD] [OK] Found file input via form context",
  "[ASYNC_UPLOAD] [OK] Found file input via dialog structure",
  "[ASYNC_UPLOAD] 🏗️ Strategy 2: Dialog structure search...",
  "[ASYNC_UPLOAD] Input has no accept attribute, but type='file' - considering valid",
  "[ASYNC_UPLOAD] Input validation passed",
  "[ASYNC_UPLOAD] [WARN] No file input found with any adaptive strategy",
  "xpath=..",
  "[ASYNC_UPLOAD] [CLIPBOARD] Strategy 1: Semantic attributes search...",
  "[ASYNC_UPLOAD] Input supports multiple files - good sign",
  "[ASYNC_UPLOAD] [SEARCH] Starting adaptive file input search...",
  "[ASYNC_UPLOAD] [OK] Found valid file input inside dialog",
  "form[enctype=\"multipart/form-data\"]",
  "[ASYNC_UPLOAD] [OK] Found file input via button search",
  "[ASYNC_UPLOAD] [FAIL] No file dialog detected",
  "[ASYNC_UPLOAD] [SEARCH] Checking for file dialog...",
  "[ASYNC_UPLOAD] [OK] Found valid file input inside form within dialog",
  "form[method=\"POST\"]",
  "[ASYNC_UPLOAD] [OK] Found file input via CSS patterns",
  "input[type=\"file\"]",
  "[ASYNC_UPLOAD] [TEXT] Strategy 4: Form context search..."
]
}

CROP_SELECTORS: Dict[str, List[str]] = {
    "crop": [
  "[ASYNC_CROP] [WARN] Reels dialog still visible, trying to close it...",
  "[ASYNC_CROP] 📐 [SVG] Searching by SVG content analysis...",
  "[ASYNC_CROP] [WARN] Adaptive crop handling failed, video may proceed with default crop",
  "[ASYNC_CROP] [FAIL] All strategies failed - crop button not found",
  "[ASYNC_CROP] [OK] Original aspect ratio selected successfully",
  "[ASYNC_CROP] 📐 Starting adaptive crop handling...",
  "[ASYNC_CROP] 📐 [SEMANTIC] Searching by semantic attributes...",
  "[ASYNC_CROP] 🖼️ Starting ADAPTIVE crop handling...",
  "[ASYNC_CROP] 📐 [FALLBACK] Using fallback patterns...",
  "aria-label",
  "[ASYNC_CROP] 📐 [CONTEXT] Searching by context analysis...",
  "[ASYNC_CROP] [WARN] Failed to select original aspect ratio",
  "xpath=ancestor::button[1] | xpath=ancestor::div[@role=\"button\"][1]",
  "[ASYNC_CROP] [SEARCH] Verifying crop page...",
  "[ASYNC_CROP] [WARN] No crop indicators found",
  "[ASYNC_CROP] ℹ️ Not on crop page or crop not needed, skipping crop handling",
  "[ASYNC_CROP] 📐 [CLICK] [OK] Successfully clicked crop button",
  "[ASYNC_CROP] 📐 Looking for 'Оригинал' (Original) aspect ratio option...",
  "[ASYNC_CROP] 📐 [CLICK] Performing human-like click on crop button...",
  "[ASYNC_CROP] 📐 [ORIGINAL] [WARN] All strategies failed to find 'Оригинал' option",
  "[ASYNC_CROP] [OK] Crop handled successfully with adaptive method"
]
}

LOGIN_SELECTORS: Dict[str, List[str]] = {
    "login": [
  "📧 [ASYNC_LOGIN] Email field input required",
  "[FAIL] [ASYNC_LOGIN] 2FA verification failed",
  "[FAIL] [ASYNC_LOGIN] No logged-in indicators found - login may have failed",
  "[OK] [ASYNC_LOGIN] Email field verification completed successfully",
  "[FAIL] [ASYNC_LOGIN] Login button not found",
  "[FAIL] [ASYNC_LOGIN] Password field not found",
  "[WARN] [ASYNC_LOGIN] Still on challenge page after captcha solving",
  "[BLOCK] [ASYNC_LOGIN] Account suspension detected in login response",
  "[FAIL] [ASYNC_LOGIN] Failed to login to Instagram",
  "[FAIL] [ASYNC_LOGIN] Still on login page - login likely failed",
  "[FAIL] [ASYNC_EMAIL] Email verification code input not found",
  "[FAIL] [ASYNC_LOGIN] Username field not found",
  "[OK] [ASYNC_2FA] 2FA authentication successful - redirected from 2FA page",
  "📧 [ASYNC_EMAIL] Submit button not found - trying Enter key",
  "[PHONE] [ASYNC_LOGIN] 2FA/Authenticator verification required",
  "[OK] [ASYNC_LOGIN] No verification required - checking if truly logged in...",
  "🔐 [ASYNC_LOGIN] Clicking login button...",
  "[OK] [ASYNC_LOGIN] Successfully passed challenge page",
  "[OK] [ASYNC_LOGIN] Login completed successfully",
  "[OK] [ASYNC_LOGIN] reCAPTCHA handling completed",
  "[OK] [ASYNC_LOGIN] 2FA verification completed successfully",
  "📧 [ASYNC_EMAIL] Clicked submit button",
  "[FAIL] [ASYNC_LOGIN] Post-login reCAPTCHA solving failed, terminating login flow",
  "[SEARCH] [ASYNC_LOGIN] Checking for reCAPTCHA on login page...",
  "[OK] [ASYNC_LOGIN] Captcha solved on challenge page",
  "[role=\"alert\"], .error-message, ._aa4a",
  "[SEARCH] [ASYNC_LOGIN] Checking for verification requirements...",
  "[WAIT] [ASYNC_LOGIN] Ensuring page is fully loaded before login check...",
  "[FAIL] [ASYNC_LOGIN] Email verification failed",
  "[FAIL] [ASYNC_LOGIN] Email field verification failed",
  "[OK] [ASYNC_LOGIN] Login flow completed successfully",
  "[OK] [ASYNC_LOGIN] Login successful",
  "[TEXT] [ASYNC_LOGIN] Filling credentials...",
  "[FAIL] [ASYNC_LOGIN] Email verification failed - LOGIN NOT COMPLETED",
  "[OK] [ASYNC_EMAIL] Email verification successful",
  "[ASYNC_SAVE_LOGIN] Checking for 'Save login info' dialog...",
  "[ASYNC_SAVE_LOGIN] [OK] Successfully clicked save login info button",
  "[ASYNC_SAVE_LOGIN] [WARN] Could not find save button, looking for 'Not now' button...",
  "[BLOCK] [ASYNC_LOGIN] Account suspended detected during login",
  "[SEARCH] [ASYNC_LOGIN] Checking login completion...",
  "[SEARCH] [ASYNC_LOGIN] Checking for 2FA/Email verification...",
  "[ASYNC_SAVE_LOGIN] No save login dialog found or handled",
  "[FAIL] [ASYNC_LOGIN] Login not completed - unknown state",
  "[ALERT] [ASYNC_LOGIN] On challenge page - attempting to solve captcha...",
  "[PHONE] [ASYNC_2FA] Handling 2FA authentication...",
  "[FAIL] [ASYNC_EMAIL] Failed to get email verification code",
  "div[role=\"alert\"], .error-message, [data-testid=\"login-error\"]",
  "[FAIL] [ASYNC_LOGIN] reCAPTCHA solving failed, terminating login flow",
  "[ASYNC_SAVE_LOGIN] [OK] Successfully clicked 'Not now' button",
  "[WAIT] [ASYNC_LOGIN] Waiting after filling credentials before form submission...",
  "[FAIL] [ASYNC_2FA] 2FA required but no secret provided",
  "[FAIL] [ASYNC_EMAIL] Email credentials not provided for verification",
  "[FAIL] [ASYNC_LOGIN] Login failed",
  "📧 [ASYNC_EMAIL] Starting email verification...",
  "[ASYNC_SAVE_LOGIN] 💾 Save login info dialog found",
  "[FAIL] [ASYNC_2FA] Failed to get 2FA code from API",
  "button[type=\"submit\"], button:has-text(\"Confirm\"), button:has-text(\"Подтвердить\")",
  "[FAIL] [ASYNC_2FA] 2FA code input not found",
  "[FAIL] [ASYNC_LOGIN] Post-login verification failed",
  "🔑 [ASYNC_LOGIN] User not logged in - need to login to Instagram",
  "[SEARCH] [ASYNC_LOGIN] Checking for post-login reCAPTCHA...",
  "[OK] [ASYNC_LOGIN] Email verification completed successfully",
  "📧 [ASYNC_LOGIN] Email verification code required",
  "[FAIL] [ASYNC_LOGIN] Failed to solve captcha on challenge page",
  "🔑 [ASYNC_LOGIN] Starting enhanced login flow..."
]
}

__all__ = ["UPLOAD_SELECTORS", "DIALOG_SELECTORS", "CROP_SELECTORS", "LOGIN_SELECTORS"]
