# Generated by Django 5.1.5 on 2025-10-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokproxy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokproxy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
