# Generated by Django 5.1.5 on 2025-10-04 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_uploader', '0002_tiktokproxy_created_at_tiktokproxy_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadaccount',
            name='proxy',
            field=models.ForeignKey(blank=True, help_text='Прокси, используемый для этой задачи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_used_in', to='tiktok_uploader.tiktokproxy'),
        ),
        migrations.AddField(
            model_name='cookierobottaskaccount',
            name='proxy',
            field=models.ForeignKey(blank=True, help_text='Прокси, используемый для обновления cookies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookie_used_in', to='tiktok_uploader.tiktokproxy'),
        ),
        migrations.AddField(
            model_name='followtarget',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Полное имя пользователя', max_length=255),
        ),
        migrations.AddField(
            model_name='followtarget',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Приватный ли аккаунт'),
        ),
        migrations.AddField(
            model_name='followtarget',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Верифицирован ли аккаунт'),
        ),
        migrations.AddField(
            model_name='followtarget',
            name='profile_pic_url',
            field=models.URLField(blank=True, default='', help_text='URL аватарки'),
        ),
        migrations.AddField(
            model_name='followtarget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='followtarget',
            name='user_id',
            field=models.CharField(blank=True, help_text='TikTok user ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='followtaskaccount',
            name='last_target_id',
            field=models.IntegerField(blank=True, help_text='ID последнего обработанного таргета', null=True),
        ),
        migrations.AddField(
            model_name='followtaskaccount',
            name='proxy',
            field=models.ForeignKey(blank=True, help_text='Прокси, используемый для подписок', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_used_in', to='tiktok_uploader.tiktokproxy'),
        ),
        migrations.AddField(
            model_name='warmuptaskaccount',
            name='proxy',
            field=models.ForeignKey(blank=True, help_text='Прокси, используемый для прогрева', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warmup_used_in', to='tiktok_uploader.tiktokproxy'),
        ),
    ]
