# Generated by Django 5.1.5 on 2025-10-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_uploader', '0003_bulkuploadaccount_proxy_cookierobottaskaccount_proxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warmuptask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warmuptask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
