# Generated by Django 5.1.5 on 2025-10-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_uploader', '0005_tiktokserver_servertask_serverhealthlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccount',
            name='tag',
            field=models.CharField(blank=True, help_text='Тематика/категория аккаунта (например: fim, memes, cooking, sports и т.д.)', max_length=100, null=True),
        ),
    ]
