# Generated by Django 5.1.5 on 2025-10-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_uploader', '0006_tiktokaccount_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега (например: memes, fim, cooking)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Описание тега (опционально)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Tag',
                'verbose_name_plural': 'Account Tags',
                'ordering': ['name'],
            },
        ),
    ]
