# Generated by Django 5.1.5 on 2025-09-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_client_agency_alter_client_user'),
        ('cabinet', '0002_calculationhistory'),
    ]

    operations = [
    ]
