# Generated by Django 5.1.5 on 2025-09-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_merge_20250910_1126'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calculationhistory',
            new_name='cabinet_cal_user_id_e9564e_idx',
            old_name='cabinet_cal_user_id_fd8459_idx',
        ),
        migrations.RenameIndex(
            model_name='calculationhistory',
            new_name='cabinet_cal_agency__bb462c_idx',
            old_name='cabinet_cal_agency__b5d65a_idx',
        ),
    ]
