# Generated by Django 5.1.5 on 2025-09-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_rename_cabinet_cal_user_id_fd8459_idx_cabinet_cal_user_id_e9564e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationhistory',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
