# Generated by Django 4.2.10 on 2025-05-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='last_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
