# Generated by Django 5.1.5 on 2025-05-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_remove_browserfingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DolphinCookieRobotTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('urls', models.JSONField(default=list)),
                ('headless', models.BooleanField(default=True)),
                ('imageless', models.BooleanField(default=False)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookie_robot_tasks', to='uploader.instagramaccount')),
            ],
            options={
                'verbose_name': 'Dolphin Cookie Robot Task',
                'verbose_name_plural': 'Dolphin Cookie Robot Tasks',
            },
        ),
    ]
