# Generated by Django 5.1.5 on 2025-05-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0012_dolphincookierobottask'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadtask',
            name='default_location',
            field=models.CharField(blank=True, default='', help_text='Локация для всех видео (необязательно)', max_length=200),
        ),
        migrations.AddField(
            model_name='bulkuploadtask',
            name='default_mentions',
            field=models.TextField(blank=True, default='', help_text='Упоминания для всех видео, по одному на строку (необязательно)'),
        ),
        migrations.AddField(
            model_name='bulkvideo',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Локация для этого видео (переопределяет общую)', max_length=200),
        ),
        migrations.AddField(
            model_name='bulkvideo',
            name='mentions',
            field=models.TextField(blank=True, default='', help_text='Упоминания для этого видео, по одному на строку (переопределяет общие)'),
        ),
    ]
