# Generated by Django 5.1.5 on 2025-08-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0017_add_suspended_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadaccount',
            name='uploaded_failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkuploadaccount',
            name='uploaded_success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bulkuploadtask',
            name='default_location',
            field=models.CharField(blank=True, default='', help_text='Location template to copy to videos (not applied automatically)', max_length=200),
        ),
        migrations.AlterField(
            model_name='bulkuploadtask',
            name='default_mentions',
            field=models.TextField(blank=True, default='', help_text='Mentions template to copy to videos (not applied automatically)'),
        ),
        migrations.AlterField(
            model_name='bulkvideo',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Location for this video (overrides default)', max_length=200),
        ),
        migrations.AlterField(
            model_name='bulkvideo',
            name='mentions',
            field=models.TextField(blank=True, default='', help_text='Mentions for this video, one per line (overrides default)'),
        ),
    ]
