# Generated by Django 5.1.5 on 2025-08-11 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0018_biolinkchangetask_biolinkchangetaskaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Warmup Task', max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('delay_min_sec', models.IntegerField(default=15)),
                ('delay_max_sec', models.IntegerField(default=45)),
                ('concurrency', models.IntegerField(default=1)),
                ('feed_scroll_min_count', models.IntegerField(default=1)),
                ('feed_scroll_max_count', models.IntegerField(default=3)),
                ('like_min_count', models.IntegerField(default=0)),
                ('like_max_count', models.IntegerField(default=3)),
                ('view_stories_min_count', models.IntegerField(default=0)),
                ('view_stories_max_count', models.IntegerField(default=5)),
                ('follow_min_count', models.IntegerField(default=0)),
                ('follow_max_count', models.IntegerField(default=2)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warmup_tasks', to='uploader.followcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WarmupTaskAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('log', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_tasks', to='uploader.instagramaccount')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warmup_used_in', to='uploader.proxy')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='uploader.warmuptask')),
            ],
        ),
    ]
