# Generated by Django 5.1.5 on 2025-08-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0020_followcategory_followtask_followtaskaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followtask',
            name='follow_max_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='followtask',
            name='follow_min_count',
            field=models.IntegerField(default=3),
        ),
    ]
