# Generated by Django 5.1.5 on 2025-08-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0020_alter_instagramaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Reels Upload', max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIALLY_COMPLETED', 'Partially Completed')], default='PENDING', max_length=20)),
                ('delay_min_sec', models.IntegerField(default=15)),
                ('delay_max_sec', models.IntegerField(default=45)),
                ('concurrency', models.IntegerField(default=1)),
                ('default_caption', models.TextField(blank=True, default='')),
                ('default_location', models.CharField(blank=True, default='', max_length=200)),
                ('default_mentions', models.TextField(blank=True, default='')),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReelsTaskAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PHONE_VERIFICATION_REQUIRED', 'Phone Verification Required'), ('HUMAN_VERIFICATION_REQUIRED', 'Human Verification Required'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=30)),
                ('log', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_success_count', models.IntegerField(default=0)),
                ('uploaded_failed_count', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels_tasks', to='uploader.instagramaccount')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels_used_in', to='uploader.proxy')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='uploader.reelstask')),
            ],
        ),
        migrations.CreateModel(
            name='ReelsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='bot/reels/')),
                ('order', models.IntegerField(default=0)),
                ('caption', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('mentions', models.TextField(blank=True, default='', help_text='One @username per line')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='uploader.reelstask')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
